import { HabitTemplate } from '../types';

export const habitTemplates: HabitTemplate[] = [
  // Health & Fitness
  {
    name: 'Drink Water',
    description: 'Stay hydrated throughout the day',
    icon: '💧',
    color: '#3B82F6',
    type: 'good',
    goal: { value: 8, unit: 'count', customUnitName: 'glasses' },
    schedule: { type: 'daily' },
    category: 'health',
  },
  {
    name: 'Exercise',
    description: 'Daily physical activity',
    icon: '💪',
    color: '#EF4444',
    type: 'good',
    goal: { value: 30, unit: 'minutes' },
    schedule: { type: 'daily' },
    category: 'health',
  },
  {
    name: 'Daily Steps',
    description: 'Hit your step goal',
    icon: '👟',
    color: '#10B981',
    type: 'good',
    goal: { value: 10000, unit: 'steps' },
    schedule: { type: 'daily' },
    category: 'health',
  },
  {
    name: 'Sleep 8 Hours',
    description: 'Get quality rest',
    icon: '😴',
    color: '#8B5CF6',
    type: 'good',
    goal: { value: 8, unit: 'hours' },
    schedule: { type: 'daily' },
    category: 'health',
  },
  {
    name: 'Meditate',
    description: 'Practice mindfulness',
    icon: '🧘',
    color: '#06B6D4',
    type: 'good',
    goal: { value: 10, unit: 'minutes' },
    schedule: { type: 'daily' },
    category: 'wellness',
  },
  {
    name: 'Stretch',
    description: 'Improve flexibility',
    icon: '🤸',
    color: '#F59E0B',
    type: 'good',
    goal: { value: 15, unit: 'minutes' },
    schedule: { type: 'daily' },
    category: 'health',
  },
  {
    name: 'Take Vitamins',
    description: 'Daily supplements',
    icon: '💊',
    color: '#EC4899',
    type: 'good',
    goal: { value: 1, unit: 'count' },
    schedule: { type: 'daily' },
    category: 'health',
  },

  // Productivity
  {
    name: 'Read',
    description: 'Daily reading habit',
    icon: '📚',
    color: '#14B8A6',
    type: 'good',
    goal: { value: 30, unit: 'minutes' },
    schedule: { type: 'daily' },
    category: 'productivity',
  },
  {
    name: 'Study',
    description: 'Learning time',
    icon: '📖',
    color: '#6366F1',
    type: 'good',
    goal: { value: 1, unit: 'hours' },
    schedule: { type: 'daily' },
    category: 'productivity',
  },
  {
    name: 'Write',
    description: 'Daily writing practice',
    icon: '✍️',
    color: '#8B5CF6',
    type: 'good',
    goal: { value: 500, unit: 'count', customUnitName: 'words' },
    schedule: { type: 'daily' },
    category: 'productivity',
  },
  {
    name: 'Practice Skill',
    description: 'Deliberate practice',
    icon: '🎯',
    color: '#F97316',
    type: 'good',
    goal: { value: 30, unit: 'minutes' },
    schedule: { type: 'daily' },
    category: 'productivity',
  },
  {
    name: 'Review Goals',
    description: 'Weekly goal review',
    icon: '🎯',
    color: '#0EA5E9',
    type: 'good',
    goal: { value: 1, unit: 'count' },
    schedule: { type: 'weekly', weeklyTarget: 1 },
    category: 'productivity',
  },
  {
    name: 'Plan Tomorrow',
    description: 'Evening planning',
    icon: '📝',
    color: '#84CC16',
    type: 'good',
    goal: { value: 1, unit: 'count' },
    schedule: { type: 'daily' },
    category: 'productivity',
  },

  // Wellness
  {
    name: 'Gratitude Journal',
    description: 'Write what you\'re grateful for',
    icon: '🙏',
    color: '#F59E0B',
    type: 'good',
    goal: { value: 3, unit: 'count', customUnitName: 'things' },
    schedule: { type: 'daily' },
    category: 'wellness',
  },
  {
    name: 'No Social Media',
    description: 'Avoid mindless scrolling',
    icon: '📱',
    color: '#EF4444',
    type: 'bad',
    goal: { value: 1, unit: 'count' },
    schedule: { type: 'daily' },
    category: 'wellness',
  },
  {
    name: 'No Junk Food',
    description: 'Eat healthy',
    icon: '🍔',
    color: '#DC2626',
    type: 'bad',
    goal: { value: 1, unit: 'count' },
    schedule: { type: 'daily' },
    category: 'wellness',
  },
  {
    name: 'Screen Time Limit',
    description: 'Reduce screen time',
    icon: '📺',
    color: '#7C3AED',
    type: 'bad',
    goal: { value: 2, unit: 'hours' },
    schedule: { type: 'daily' },
    category: 'wellness',
  },
  {
    name: 'Practice Mindfulness',
    description: 'Be present in the moment',
    icon: '🌸',
    color: '#EC4899',
    type: 'good',
    goal: { value: 10, unit: 'minutes' },
    schedule: { type: 'daily' },
    category: 'wellness',
  },

  // Self-Care
  {
    name: 'Skincare Routine',
    description: 'Daily skincare',
    icon: '✨',
    color: '#06B6D4',
    type: 'good',
    goal: { value: 1, unit: 'count' },
    schedule: { type: 'daily' },
    category: 'self-care',
  },
  {
    name: 'Floss',
    description: 'Dental hygiene',
    icon: '🦷',
    color: '#10B981',
    type: 'good',
    goal: { value: 1, unit: 'count' },
    schedule: { type: 'daily' },
    category: 'self-care',
  },
  {
    name: 'Wake Up Early',
    description: 'Start your day right',
    icon: '🌅',
    color: '#F59E0B',
    type: 'good',
    goal: { value: 1, unit: 'count' },
    schedule: { type: 'daily' },
    category: 'self-care',
  },
  {
    name: 'Go Outside',
    description: 'Get fresh air and sunlight',
    icon: '🌳',
    color: '#22C55E',
    type: 'good',
    goal: { value: 30, unit: 'minutes' },
    schedule: { type: 'daily' },
    category: 'self-care',
  },
];

export const getTemplatesByCategory = (category: string): HabitTemplate[] => {
  return habitTemplates.filter(t => t.category === category);
};

export const searchTemplates = (query: string): HabitTemplate[] => {
  const lowerQuery = query.toLowerCase();
  return habitTemplates.filter(
    t => t.name.toLowerCase().includes(lowerQuery) ||
         t.description.toLowerCase().includes(lowerQuery)
  );
};
